### ISSUE TITLE
table-arrows mode shows arrows on initial load when no sorting enabled

### ISSUE THREAD

**Issue by mvl22** [LeeWannacott/table-sort-js#123]
On first load of a table with table-arrows mode on, there are up-arrows shown, even though sorting is not in place. This is confusing, as it implies that the rows are sorted, when in fact they are not.

Clicking on a column then sorts the column, retaining the up-arrow. A second click then switches to the down-arrow sort.

The behaviour should be adjusted so that the initial load shows no arrows, and the arrows appear on first sort click. From then on, the rest of the behaviour is correct.

**Comment by LeeWannacott** [comment]
Yep, there should either be a up/down arrow; something like for example:
* 2195	 ↕ 	Up Down Arrow

Or it should display either a down or up arrow on hover (semi-transparent) and once clicked become solid even when not hovered...

If you go with no arrows you need to make sure the space exists before adding the arrows otherwise it will noticeably mess with the column width when you click column header...

**Comment by mvl22** [comment]
Yes, that would be a good icon to use.

I did think about that spacing issue - a project I currently have some ancient JS code in, that I am keen to use your package for instead, has this problem. I should have noted it, sorry.

It does I suppose reduce down the choice of icons available for the up/down as there seem to be few up-down glyphs across the various unicode sets. The one you selected I think would work brilliantly though.

**Comment by LeeWannacott** [comment]
![image](https://github.com/LeeWannacott/table-sort-js/assets/49783296/6827ea7d-1fcf-483b-afc4-a5d2605ab232)
1.18.3: arrows now look like this.

**Comment by LeeWannacott** [comment]
I may need to change it so that when clicking on another column it resets the other columns to  `↕`.
