### ISSUE TITLE
Chrome browser extension not working?

### ISSUE THREAD

**Issue by nicoleahmed** [LeeWannacott/table-sort-js#125]
Chrome: Version 120.0.6099.225 (Official Build) (64-bit)
table-sort-js: Version 1.18.3

Hi
The web demos look great. Have installed on Chrome and I don't seem to be able to make any tables sortable.

On this page I can click the headings of the table on the bottom but nothing happens. First table nothing at all: https://www.shareprogress.org/bookmarklet/htmltabletest/

On this page I can click headings but the sort is broken:
https://www.gov.uk/government/publications/local-stop-smoking-services-and-support-additional-funding/local-stop-smoking-services-and-support-funding-allocations-and-methodology#smoking-prevalence-and-confirmed-funding-allocations-by-local-authority

Also there are no icons on the header like in your demo:
![noiconsheader](https://github.com/LeeWannacott/table-sort-js/assets/38244338/292fe395-ed7b-4d1f-b924-db02fbcc6018)

Sorry if this is user error...

**Comment by LeeWannacott** [comment]
Hi @nicoleahmed,

> On this page I can click the headings of the table on the bottom but nothing happens. First table nothing at all: https://www.shareprogress.org/bookmarklet/htmltabletest/


Looks like they are using `<td>` (meant for cells in the table body)  inside the `<thead>` (table head) rather than `<th>` (table header cells) which is for table columns. Another-words they are doing semantically incorrect HTML. However, I should still handle this case because I think it happens a bit and its probably an easy fix.

> On this page I can click headings but the sort is broken:
https://www.gov.uk/government/publications/local-stop-smoking-services-and-support-additional-funding/local-stop-smoking-services-and-support-funding-allocations-and-methodology#smoking-prevalence-and-confirmed-funding-allocations-by-local-authority

I'm not 100% sure what is going on with this one, but I would suspect its because in every table row in the table body they have a `<th>` at the start of the table row which is the local authority in bold for each row. I'm not sure why this would break the sort my intuition tells me its sorting the data from other columns than the one you are clicking on (which might be why the last column doesn't sort at all). Although there might be more going on like `numeric-sort` class not handling pounds ,or something. 

> Also there are no icons on the header like in your demo:

The icons come from the `table-arrows` class. The browser extensions are pretty primitive they just put `table-sort` class on each table on the page which allows table-sort-js to run. Maybe in the future could have toggles on the extension for if the user wants to see arrows or not..

I'll probably get around to fixing it at some point can't make any guarantees though.

Cheers.

**Comment by LeeWannacott** [comment]
Fixed the first table not working in `v1.19.0`: https://www.shareprogress.org/bookmarklet/htmltabletest/ 
Have to wait for it to pass chromes annoying extension review though :zzz: ; is available and seems to work on firefox though. Issue: https://github.com/LeeWannacott/table-sort-js/issues/126

**Comment by LeeWannacott** [comment]
> https://www.gov.uk/government/publications/local-stop-smoking-services-and-support-additional-funding/local-stop-smoking-services-and-support-funding-allocations-and-methodology#smoking-prevalence-and-confirmed-funding-allocations-by-local-authority

I partially fixed this in v1.20.0 at least the columns match up to the sort now; numeric-sort inference needs to be fixed so that it also handles numbers with pound sign in the front of it.

**Comment by LeeWannacott** [comment]
@nicoleahmed table-sort-js v1.21.0 (available on chrome store) now supports currency and percentage signs. 

The table below seems to correctly sort now:
https://www.gov.uk/government/publications/local-stop-smoking-services-and-support-additional-funding/local-stop-smoking-services-and-support-funding-allocations-and-methodology#smoking-prevalence-and-confirmed-funding-allocations-by-local-authority 

Thanks, for being specific with your issue and linking me an actual table, so I could fix it (https://addons.mozilla.org/en-US/firefox/addon/table-sort-js/reviews/ like how am I suppose do diagnose from these reviews :face_exhaling:).
