### ISSUE TITLE
Sort by units

### ISSUE THREAD

**Issue by MichaelM00** [LeeWannacott/table-sort-js#15]
Thanks for this sort library @LeeWannacott

Is it possible to add a way to sort by units such as KB/KiB, MB/MiB, GB/GiB etc? Currently the sort doesn't take these units into account if a number is prefixed to them.

**Comment by MichaelM00** [comment]
I'm not very good with JS unfortunately but would be happy to test. Perhaps converting size of units (Bytes to TB) all into bytes first, match innerText of a table cell with regex ending with specified units then calculate and sort according to unit size/cell values in bytes would be one way to go?

**Comment by LeeWannacott** [comment]
Okay, looks like I am doing this issue; erlliam is doing interview prep. 

Would you be able to send, or screenshot your data;  I assume it's all in Kilobytes like (Size column):
![table-kilobyte](https://user-images.githubusercontent.com/49783296/114821832-47245f80-9e15-11eb-8bdb-b3c9239e2dab.png)

If your data is like this screenshot (All in KB and just a number no suffix) we could sort by kilobytes and then convert to MB, GB and TB (if not we can convert before sending to sort function)? Regex can be a bit flaky sometimes; probably just want to ask if the string includes MB, GB, or TB, rather than just the end of the string.

I have to make a design decision whether to make this specific to file size sorting, or make it generalize to sorting different unit types. Looks like a fun issue. Thanks.

**Comment by LeeWannacott** [comment]
@MichaelM00 . This is what I have so far, if you want to test it: b7bcdf19a9a7071c2ae98bef55f256a3e879fe00 
Download table-sort.js from the public folder and add it to a script tag to test on your data. Use class="file-size" on the <th>.

I haven't done KiB, MiB, GiB; could change to that instead of KB,MB,GB ?, or can maybe add an option?.
Probably want it to two decimal places?; I don't know how accurate you want your data?
Let me know what changes you want me to make. (I'll refactor the code later and deploy once the code is polished)

Example:
![file-size-sorting](https://user-images.githubusercontent.com/49783296/114956275-a4bab980-9eb2-11eb-9dc2-9382f35ee109.png)

**Comment by LeeWannacott** [comment]
Changed to binary prefix(KiB) rather than metric(KB); Also fixed some broken logic. d066c1f24b06bb996ae2ba873b1cee637a43fbad
If you want to test download table-sort.js from the public folder.

**Comment by MichaelM00** [comment]
My table data are like below
```
100.00 B
100.50 KiB
1.50 GiB
100.50 MiB
1000.50 KiB
```
I guess for general purposes it might be best to match any number of decimal numbers and either metric/binary units.

I tested the sort but when sorting it gives `NaN` or `NaNTiB` (files showing this were in KiB). Not sure if it's due to the space between number and unit but it gave the same errors when removing the space from the table data.

**Comment by MichaelM00** [comment]
The issue might be with inner tags such as `<td><center>100.50 KiB</center></td>` as once they were removed sorting worked.

When testing I also noticed table data with size such as `100.00 B` weren't sorted properly.

**Comment by LeeWannacott** [comment]
I implemented B/Bytes. Inner tags won't return NaN now. however the inner tags won't apply i.e it won't center(I need to figure out how to get the tags and wrap them around it), Inner tags work for normal data though i.e not using file-size.

**Comment by MichaelM00** [comment]
>I'm guessing you want it to produce a space between the number and the units ? 

Yup (or rather keep the space only if it's already there). 

Hopefully there is a way to keep the tags working properly while sorting the file size. I will keep testing and see if I come across any bugs/way to keep the tags.

**Comment by LeeWannacott** [comment]
The inner tags should be kept now; However using them with React breaks the conversion for some reason :facepalm:.  
I changed to convert to bytes instead of Kibibytes. Meaning it will sort B -> TiB. I still need to change the regex to account for a space between the unit-type and account for empty values.

**Comment by LeeWannacott** [comment]
Okay have accounted for having a space in front of unit-type and outputs to number space unit (e.g 155 KB) and empty values are now sorted properly. Test it out :test_tube: , should :crossed_fingers:  do what you want now.

**Comment by MichaelM00** [comment]
Thanks @LeeWannacott, did a quick test and it is working now!
