### ISSUE TITLE
Bug: Incorrectly ordering when colspan attribute is used

### ISSUE THREAD

**Issue by msebela** [LeeWannacott/table-sort-js#58]
If attribute `colspan` is used in the table header, the following columns are not ordered correctly.

```
<th scope="col">Column 1</th>                 <- sorted correctly
<th scope="col" colspan="2">Column 2</th>     <- sorted correctly
<th scope="col">Column 3</th>                 <- sorted incorrectly (sorted by "Column 2")
<th scope="col">Column 4</th>                 <- sorted incorrectly (sorted by "Column 3")
```

**Comment by LeeWannacott** [comment]
Hey @msebela Yeah, I see what you mean; Thanks for reporting this.  

I'm busy working on other stuff at the moment; but, hopefully I'll get round to fixing it at some point: :crossed_fingers:

**Comment by scodes73** [comment]
Hey @LeeWannacott, Can I take a look at it?, and @msebela can you elaborate more on the issue ( I tried adding colspan but couldn't see what you're implying. ) Thank you.

**Comment by LeeWannacott** [comment]
@scodes73 Sure feel free to have a look at it. I'm currently working on something else, but I'm happy to answer any questions and look at PR's.

I did have a look at what the problem is. If @msebela doesn't message you back; perhaps you can figure it out by messing around with the example below (try sorting on column 3, also notice how column 5 is blank):
``` html
<!DOCTYPE html>
<html lang="en">
<script src="table-sort.js"></script>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
   <table class="table-sort table-arrows">
      <thead>
        <tr>
      <th scope="col">Column 1</th>               
      <th scope="col" colspan="2">Column 2</th>    
      <th scope="col">Column 3</th>              
      <th scope="col">Column 4</th>             
      <th scope="col">Column 5</th>             
        </tr>
      </thead>
      <tr>
        <td>Franklin</td>
        <td>benjamin</td>
        <td>1706,1,17</td>
        <td>1</td>
        <td>C-level</td>
      </tr>
      <tr>
        <td>da Vinci</td>
        <td>Zarlo</td>
        <td>1452.4.15</td>
        <td>3</td>
        <td></td>
      </tr>
      <tr>
        <td>Statham</td>
        <td></td>
        <td>1967-7-26</td>
        <td>2</td>
        <td>HR</td>
      </tr>
      <tr>
        <td>Micheal</td>
        <td></td>
        <td>1958/8/21</td>
        <td>54</td>
        <td>Marketing</td>
      </tr>

      <tr>
        <td>Ben</td>
        <td></td>
        <td>1994/9/23</td>
        <td>134</td>
        <td>Marketing</td>
      </tr>
    </table>
</body>
</html>
```

Thanks.

**Comment by scodes73** [comment]
@LeeWannacott I've fixed it in the PR https://github.com/LeeWannacott/table-sort-js/pull/59, could you guide me on testing part.

**Comment by LeeWannacott** [comment]
@scodes73 Well looks like it doesn't break anything on CI which is a good sign!; I assume sap-zem is also you?

@scodes73  Sure. Do you need guidance on how to run the tests? (https://leewannacott.github.io/table-sort-js/docs/development.html I wrote some instructions on that there), or on what the test for this should look like?

I think for this issue you might need to change test/table.js;  so that it supports having multiple columns and simulating clicks on different columns.

`function createTestTable(testTableData, classTags = "", invisibleIndex = []) {` You might need to add a parameter that is an object that can contain classTags, scope, colspan etc.`

I'm a have a think about how to test this and I'll add more comments if I think of anything.

**Comment by scodes73** [comment]
@LeeWannacott  Sure, I'll look into the testing part, I'll try modifying the test/table.js. (Yes sap-zem is also me). I am going to look at createTestTable(...) function.

**Comment by LeeWannacott** [comment]
@scodes73  Hit me up if you need anything; I'll be awake for another 2-3 hours. 

Sorry this PR is a little bit involved because it requires changes to how the testing is done; because currently it is only setup to test one column, whereas we need to really test multiple for this issue (it would also be helpful for doing tests for the remember-sort tag; I think I was a part of the no test, low test movement at that time...).

**Comment by scodes73** [comment]
@LeeWannacott Yeah, I'll be taking a look at the testing now, I haven't given it a look yet. Feel free to commit to this PR as well.

**Comment by LeeWannacott** [comment]
Do you want me to set the testing up for multiple columns (It might take me while)?, or we can pair program it? and you can write the test just for this issue, or something?

**Comment by scodes73** [comment]
@LeeWannacott Yes please go ahead, do your part as much as you can, I'll extend to it. Thank You.

**Comment by LeeWannacott** [comment]
@scodes73 I can give it a go; however it might be a job for tomorrow though (if you don't mind waiting a day).

**Comment by scodes73** [comment]
@LeeWannacott No issues, please do.

**Comment by scodes73** [comment]
@LeeWannacott Any update on this?

**Comment by LeeWannacott** [comment]
@scodes73 I did have a go it's a bit tricky/time consuming. I can merge your PR and then open an issue for setting up testing for multiple columns and then open a separate issue writing tests for colspan and remember sort...

**Comment by scodes73** [comment]
@LeeWannacott Yes, go ahead and merge it.
