### ISSUE TITLE
Numbers do not sort correctly with differing decimal counts

### ISSUE THREAD

**Issue by Osiaris** [LeeWannacott/table-sort-js#63]
When creating a table while using several decimal counts the sorting counts number of decimals as higher than a higher value, this can be seen in the provided screenshot.

![bild](https://user-images.githubusercontent.com/94265685/190573528-86932e4f-bbbd-4b05-bdfb-cc15b2ddd9da.png)

**Comment by LeeWannacott** [comment]
@Lz-01 Any progress on this?; are you still interested in this issue?

**Comment by scodes73** [comment]
Is this still a thing? Can I take a look? @LeeWannacott

**Comment by LeeWannacott** [comment]
@scodes73 Sure take a look if you want to. I will assign you so nobody else takes it; no pressure though it might be tricky.

strager is correct table-sort-js does version numbers correctly at the moment by default. I don't know what I was on about when I made this issue:
![image](https://github.com/LeeWannacott/table-sort-js/assets/49783296/aa8ff514-683f-48aa-94bb-41f1b950b7e5)

For semantic versioning on a file number .18 is higher than .9 However for a decimal number .18 is lower than .9 

There is an issue just not with release versions/ file versions.

So basically you would need to make this test pass:
```
test("Sort decimal numbers", () => {
  expect(
    createTestTable(
      {
        col0: ["0.1", "0.2", "0.3", "0.11", "0.13", "0.13", "0.14"],
      },
      { classTags: "sort-numbers" }
    )
  ).toStrictEqual({
    col0: ["0.1", "0.11", "0.13", "0.13", "0.14", "0.2", "0.3"],
  });
});
```
One approach might be to pad with 0's like I did with the date classes, but you would need to know how many decimal places and I'm not sure how you would figure that out; other than having to loop over the whole column and get the number with largest decimal places (could be done in infer sort classes function, but would also need a way when manually applying the class), or setting it to the maximum value JS allows (probably not a good approach).

https://github.com/LeeWannacott/table-sort-js/issues/64
table-sort-js also doesn't support negative numbers correctly with "-" or "(" ")" because it ignores punctuation, I probably would of done this at the same time as decimals and put it on the sort-numbers class as well but you don't have to.

**Comment by scodes73** [comment]
@LeeWannacott  Yeah we could do that, what all should we be including in number-sort: plain numbers, negative numbers, normal decimals( single .). Is that it, or am I missing something else? And also should we infer those or make it mentioned explicitly, what do you think?

My take is we could infer for semantic-versioning(https://semver.org/), where this might be only the use case where multiple '.'(dot) scenario occurs. (Could also be pointed as new feature: support for semantic versioning).

**Comment by LeeWannacott** [comment]
The decimals might be a problem for currency as well @scodes73

**Comment by scodes73** [comment]
@LeeWannacott Can you take a look at https://github.com/LeeWannacott/table-sort-js/pull/87
Please let me know if I missed any corner cases.

**Comment by LeeWannacott** [comment]
Done by @scodes73 in PR https://github.com/LeeWannacott/table-sort-js/pull/87
